project:
  type: website

website:
  title: "INE Data Lab"
  back-to-top-navigation: true
  navbar:
    background: "#457E76"
    left:
      - file: api-json/inicio.qmd
        text: API JSON
      - file: api-json-stat/inicio.qmd
        text: API JSON-stat
      - file: api-censo/inicio.qmd
        text: "API Censos 2021"
      - href: https://es-ine.github.io/ineapir/
        text: "INEapir"


  sidebar:
    - id: api-json
      title: "API JSON"
      logo: img/LogoINE.svg
      logo-alt: Logo INE
      style: "docked"
      background: "#DDEEEC"
      collapse-level: 1
      contents:
        - api-json/inicio.qmd
        - api-json/referencia.qmd
        - section: "Lista de funciones"
          contents: api-json/funciones/*.qmd 
        - api-json/obtener_datos_tabla.qmd
        - api-json/otros_casos_uso.qmd
        - api-json/codigos_identificadores.qmd
        - api-json/tempus3.qmd
    
    - id: api-json-stat
      title: "API JSON-stat"
      contents:
        - api-json-stat/inicio.qmd
        - api-json-stat/referencia.qmd
        - api-json-stat/obtener_datos_tabla.qmd
        - api-json-stat/codigos_identificadores.qmd
        
    - id: api-censo
      title: "API Censos 2021"
      contents:
        - api-censo/inicio.qmd
        - api-censo/referencia.qmd
        - api-censo/peticion_datos.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
