---
title: "Obtener datos de una tabla"
---

Para obtener los datos de una tabla es necesario conocer su código identificativo (vea [códigos identificadores de tablas y series](codigos_identificadores.html)).

Una vez se conoce el código de la tabla de interés, se puede utilizar la función [DATOS_TABLA](funciones/datos_tabla.html) para obtener los datos asociados.

**Obtener todos los datos de la tabla**

Por ejemplo, para la tabla [Índices nacionales: general y de grupos ECOICOP](https://www.ine.es/jaxiT3/Tabla.htm?t=50902) (Id 50902):

<https://servicios.ine.es/wstempus/js/ES/DATOS_TABLA/50902>

**Obtener los n últimos datos**

Utilizamos el parámetro nult. Por ejemplo nult=5 para obtener los últimos 5 datos:

<https://servicios.ine.es/wstempus/js/ES/DATOS_TABLA/50902?nult=5>

## Como filtrar datos de una tabla

Cuando realizamos una petición de datos de una tabla existe la posibilidad de filtrar por variables y valores de interés utilizando el parámetro tv. Para ello vamos a distinguir los tres tipos posibles de fuentes de las tablas (tablas Tempus 3, tablas pc-axis y tablas tpx).

### Tablas Tempus 3

Para poder filtrar es necesario conocer los códigos identificadores numéricos (Id) de las variables y los valores por los que queremos filtrar. Por lo tanto, debemos hacer lo siguiente:

1.  Conocer los grupos de la tabla de interés [Índices por comunidades autónomas: general y de grupos ECOICOP](https://www.ine.es/jaxiT3/Tabla.htm?t=50913) (Id = 50913):

    <https://servicios.ine.es/wstempus/js/ES/GRUPOS_TABLA/50913>

2.  Conocer los valores de los grupos:

    <https://servicios.ine.es/wstempus/js/ES/VALORES_GRUPOSTABLA/50913/110924?det=1>

    <https://servicios.ine.es/wstempus/js/ES/VALORES_GRUPOSTABLA/50913/110925?det=1>

    <https://servicios.ine.es/wstempus/js/ES/VALORES_GRUPOSTABLA/50913/110926?det=1>

3.  Filtrar por la variables y valores que nos interesan:

    Por ejemplo, variación anual (id_variable = 3, id_valor = 74 y tv=3:74) del índice general (id_variable = 762, id_valor = 304092 y tv=762:304092) de la Comunidad de Madrid (id_variable = 70, id_valor = 9009 y tv=70:9009)

    <https://servicios.ine.es/wstempus/js/ES/DATOS_TABLA/50913?nult=2&tv=3:74&tv=762:304092&tv=70:9009>

    Si no se especifica ningún valor, se obtienen todos los valores de la variable. Por ejemplo, con tv=70: se obtiene todas las Comunidades Autónomas

    <https://servicios.ine.es/wstempus/js/ES/DATOS_TABLA/50913?nult=2&tv=3:74&tv=762:304092&tv=70:>

    Si queremos filtrar por varios valores de una misma variable, tenemos que incluir tantos parámetros tv como valores. Por ejemplo, para obtener datos tanto de la Comunidad de Madrid como del Principado de Asturias (id_variable = 70, id_valor = 8999 y tv=70:8999)

    <https://servicios.ine.es/wstempus/js/ES/DATOS_TABLA/50913?nult=2&tv=3:74&tv=762:304092&tv=70:9009&tv=70:8999>

### Tablas pc-axis

Para poder filtrar es necesario conocer los códigos identificadores alfanuméricos (Código) de las variables y los valores por los que queremos filtrar. Por lo tanto, debemos hacer lo siguiente:

1.  Pedir los metadatos de las series que conforman la tabla de interés [Población por edad (3 grupos de edad), Españoles/Extranjeros, Sexo y Año](https://www.ine.es/jaxi/Tabla.htm?path=/t20/e245/p08/l0/&file=01001.px) (Id = t20/e245/p08/l0/01001.px)

    <https://servicios.ine.es/wstempus/js/ES/SERIES_TABLA/t20/e245/p08/l0/01001.px?tip=M>

2.  Filtrar por la variables y valores que nos interesan:

    Por ejemplo, para la población de mujeres (id_variable = sexo, id_valor = mujeres, tv=sexo:mujeres) españolas (id_variable = espanolesextranjeros, id_valor = españoles, tv= espanolesextranjeros:españoles) de todas las edades (id_variable = edad3gruposdeedad, id_valor = totaledades, tv=edad3gruposdeedad:totaledades)

    <https://servicios.ine.es/wstempus/js/ES/DATOS_TABLA/t20/e245/p08/l0/01001.px?nult=2&tv=sexo:mujeres&tv=espanolesextranjeros:espanoles&tv=edad3gruposdeedad:totaledades>

    Si no se especifica ningún valor, se obtienen todos los valores de la variable. Por ejemplo, con tv=sexo: se obtiene la población de hombres, mujeres y ambos sexos

    <https://servicios.ine.es/wstempus/js/ES/DATOS_TABLA/t20/e245/p08/l0/01001.px?nult=2&tv=sexo:&tv=espanolesextranjeros:espanoles&tv=edad3gruposdeedad:totaledades>

    Si queremos filtrar por varios valores de una misma variable, tenemos que incluir tantos parámetros tv como valores. Por ejemplo, para obtener la población de hombres y mujeres

    <https://servicios.ine.es/wstempus/js/ES/DATOS_TABLA/t20/e245/p08/l0/01001.px?nult=2&tv=sexo:mujeres&tv=sexo:hombres&tv=espanolesextranjeros:espanoles&tv=edad3gruposdeedad:totaledades>

### Tablas tpx

Para poder filtrar es necesario conocer los códigos identificadores alfanuméricos de las variables y los valores por los que queremos filtrar. Por lo tanto, debemos hacer lo siguiente:

1.  Pedir los metadatos de las series que conforman la tabla de interés [Extracción nacional por tipo de material y años](https://www.ine.es/jaxi/Tabla.htm?tpx=33387&L=0)  (Id = 33387)

    <https://servicios.ine.es/wstempus/js/ES/SERIES_TABLA/33387?tip=M>

2.  Filtrar por la variables y valores que nos interesan:

    Por ejemplo, para biomasa (id_variable = tipodematerial, id_valor = tipodematerial, tv= tipodematerial: tipodematerial

    <https://servicios.ine.es/wstempus/js/ES/DATOS_TABLA/33387?nult=2&tv=tipodematerial:1biomasa>

    Si no se especifica ningún valor, se obtienen todos los valores de la variable. Por ejemplo, con tv=sexo: se obtiene la población de hombres, mujeres y ambos sexos

    <https://servicios.ine.es/wstempus/js/ES/DATOS_TABLA/33387?nult=2&tv=tipodematerial:>

    Si queremos filtrar por varios valores de una misma variable, tenemos que incluir tantos parámetros tv como valores. Por ejemplo, para obtener biomasa y minerales metálicos

    <https://servicios.ine.es/wstempus/js/ES/DATOS_TABLA/33387?nult=2&tv=tipodematerial:1biomasa&tv=tipodematerial:2mineralesmetalicosmineralenbruto>

#### Tablas tpx con códigos identificadores de Tempus 3

Existen tablas tpx que contienen códigos identificadores de Tempus 3 ([Censo agrario 2020](https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736176851&menu=resultados&idp=1254735727106)). En este caso además de filtrar usando los códigos alfanuméricos, como para una tabla tpx normal, también se puede filtrar utilizando los códigos numéricos Tempus 3 de las variables y los valores. Para ello, debemos hacer lo siguiente:

1.  Pedir lo metadatos de las series que conforman la tabla de interés [Mano de obra en la explotación, familiar y contratada de manera regular, por relación con el titular, porcentaje de unidad de trabajo-año total (UTAT) y sexo](https://www.ine.es/jaxi/Tabla.htm?tpx=52056&L=0) (Id=52056). A la función [SERIES_TABLA](#_SERIES_TABLA) también le podemos pasar un filtro (útil para tablas con un gran número de series debido a una gran segmentación territorial), por ejemplo total nacional (tv=NAC:00):

    <https://servicios.ine.es/wstempus/js/ES/SERIES_TABLA/52056?tip=M&tv=NAC:00>

2.  Para utilizar los identificadores numéricos añadimos el alias \~id al final (tv=id_varaible\~id:id_valor\~id). Por ejemplo  para el Total Nacional (tv=349\~id:16473\~id),  Total tramos UTAT (tv=916\~id:391871\~id), Nº explotaciones (tv=942\~id:274282\~id), Total mano de obra (tv=999\~id:391770\~id) y Valor absoluto (tv=3\~id:11406\~id) tendríamos:

    <https://servicios.ine.es/wstempus/js/ES/DATOS_TABLA/52056?tv=349~id:16473~id&tv=916~id:391871~id&tv=942~id:274282~id&tv=999~id:391770~id&tv=3~id:11406~id>
