---
title: "Otros casos de uso"
---

## Obtener datos de una serie

Para obtener los datos de una única serie es necesario conocer su código identificativo (vea códigos identificativos de tablas y series).

Una vez se conoce el código de la serie de interés, se puede utilizar la función [DATOS_SERIE](funciones/datos_serie.html) para obtener los datos de interés.

**Obtener el último periodo de una serie**

Por ejemplo, para la serie con código [IPC251856](https://www.ine.es/consul/serie.do?s=IPC251856)

<https://servicios.ine.es/wstempus/js/ES/DATOS_SERIE/IPC251856?nult=1>

**Obtener los últimos 5 periodos de una serie**

Por ejemplo, para la serie con código [IPC251856](https://www.ine.es/consul/serie.do?s=IPC251856)

<https://servicios.ine.es/wstempus/js/ES/DATOS_SERIE/IPC251856?nult=5>

**Obtener los datos entre dos fechas**

Por ejemplo, entre 01/01/2023 y 31/12/2023

<https://servicios.ine.es/wstempus/js/ES/DATOS_SERIE/IPC251856?date=20230101:20231231&tip=A>

**Obtener los datos a partir de una fecha**

Por ejemplo, a partir de 01/01/2024

<https://servicios.ine.es/wstempus/js/ES/DATOS_SERIE/IPC251856?date=20240101:&tip=A>

## Consultar operaciones estadísticas

La base de datos Tempus3 contiene la información de todas las operaciones estadísticas coyunturales del INE, aquellas cuya periodicidad de difusión de resultados es inferior al año, además de algunas operaciones estadísticas estructurales. La relación de operaciones en Tempus3 cambia a medida que se van integrando en la base de datos. Puede consultarse la lista de operaciones disponibles en cualquier momento con las funciones [OPERACIONES_DISPONIBLES](funciones/operaciones_disponibles.html) y [OPERACION](funciones/operacion.html).

**Obtener las operaciones estadísticas disponibles del sistema**

<https://servicios.ine.es/wstempus/js/ES/OPERACIONES_DISPONIBLES>

**Obtener una operación estadística**

Por ejemplo, la operación IPC utilizando el código alfabético Tempus3 interno (IPC)

<https://servicios.ine.es/wstempus/js/ES/OPERACION/IPC>

## Consultar variables

Se pueden obtener las variables del Sistema utilizando las funciones [VARIABLES](funciones/variables.html) y [VARIABLES_OPERACION](funciones/variables_operacion.html).

**Obtener todas las variables del sistema**

La respuesta está paginada (500 elementos por página)

<https://servicios.ine.es/wstempus/js/ES/VARIABLES>

<https://servicios.ine.es/wstempus/js/ES/VARIABLES?page=2>

**Obtener variables para una operación**

Por ejemplo, las variables utilizadas en la operación IPC

<https://servicios.ine.es/wstempus/js/ES/VARIABLES_OPERACION/IPC>

## Consultar valores de variables

Se pueden obtener los valores de una variable utilizando las funciones [VALORES_VARIABLE](funciones/valores_variable.html) y [VALORES_VARIABLEOPERACION](funciones/valores_variableoperacion.html).

**Obtener todos los valores de una variable**

Por ejemplo, de la variable Provincias (Id=115)

<https://servicios.ine.es/wstempus/js/ES/VALORES_VARIABLE/115>

**Obtener todos los valores de una variable para una operación**

Por ejemplo, los valores de la variable “Grupos ECOICOP" (Id=762) para la operación IPC (IOE30138 / IPC / 25)

<https://servicios.ine.es/wstempus/js/ES/VALORES_VARIABLEOPERACION/762/25>

## Obtener información de tablas

En lo que se refiere a las tablas, se puede obtener un listado de las tablas de una operación con la función [TABLAS_OPERACION](funciones/tabla_operacion.html) y también las variables y valores que la definen con las funciones [GRUPOS_TABLA](funciones/grupos_tabla.html) y [VALORES_GRUPOSTABLA](funciones/valores_grupostabla.html).

**Obtener todas las tablas de una operación**

Por ejemplo, el listado de tablas de la operación estadística IPC (IOE30138 / IPC / 25)

<https://servicios.ine.es/wstempus/js/ES/TABLAS_OPERACION/IPC>

**Obtener la combinación de variables y valores que definen una tabla**

Una tabla está definida por diferentes grupos o combos de selección y cada uno de ellos por los valores que toman una o varias variables. La consulta de los valores y las variables que constituyen la tabla se debe realizar en dos partes:

1.  Primera parte de la consulta: Grupos o combos de selección que definen a la tabla "[Índices por comunidades autónomas: general y de grupos ECOICOP](https://www.ine.es/jaxiT3/Tabla.htm?t=50913)" (Id 50913)

    <https://servicios.ine.es/wstempus/js/ES/GRUPOS_TABLA/50913>

2.  Segunda parte de la consulta: Valores del grupo "Comunidades y Ciudades Autónomas" (Id=110924) perteneciente a la tabla "[Índices por comunidades autónomas: general y de grupos ECOICOP](https://www.ine.es/jaxiT3/Tabla.htm?t=50913)" (Id=50913)

    <https://servicios.ine.es/wstempus/js/ES/VALORES_GRUPOSTABLA/50913/110924?det=1>

## Obtener información de series

En lo que se refiere a las series, se puede obtener información de una serie con la función [SERIE](funciones/serie.html), así como de las variables y valores que la definen con la función [VALORES_SERIE](funciones/valores_serie.html). Además, también se puede obtener un listado de las series de una tabla con la función [SERIES_TABLA](funciones/series_tabla.html) y un listado de las series de una operación [SERIES_OPERACION](funciones/series_operacion.html).

**Obtener información de una serie**

Por ejemplo, de la serie que recoge los datos del índice general del IPC ([IPC251852](https://www.ine.es/consul/serie.do?s=IPC251852)) que recoge la variación mensual del Índice de precios de consumo

<https://servicios.ine.es/wstempus/js/ES/SERIE/IPC251852?det=2&tip=A>

**Obtener las variables y valores que definen una serie**

Por ejemplo, de la serie que recoge los datos del índice general del IPC ([IPC251852](https://www.ine.es/consul/serie.do?s=IPC251852))

<https://servicios.ine.es/wstempus/js/ES/VALORES_SERIE/IPC251852?det=1>

**Obtener el listado de series de una tabla**

Por ejemplo, las series de la tabla "[Índices por comunidades autónomas: general y de grupos ECOICOP](https://www.ine.es/jaxiT3/Datos.htm?t=50913)" de la operación IPC (Id 50913).

<https://servicios.ine.es/wstempus/jsCache/ES/SERIES_TABLA/50913>

Se puede utilizar el parámetro tv para filtrar por variables y valores. Más información en [Como filtrar datos de una tabla](obtener_datos_tabla.html#como-filtrar-datos-de-una-tabla).

**Obtener el listado de series de una operación**

Como el resultado está paginado, se debe utilizar el parámetro page. Consulta de las primeras 500 series pertenecientes a la operación IPC (IOE30138 / IPC / 25)

<https://servicios.ine.es/wstempus/js/ES/SERIES_OPERACION/IPC?page=1>

Consulta de las segundas 500 series pertenecientes a la operación IPC (IOE30138 / IPC / 25)

<https://servicios.ine.es/wstempus/js/ES/SERIES_OPERACION/IPC?page=2>

## Consultar publicaciones

Se puede obtener un listado de las todas las publicaciones del sistema con la función [PUBLICACIONES](funciones/publicaciones.html), así como el listado de las publicaciones de una operación con la función [PUBLICACIONES_OPERACION](funciones/publicaciones_operacion.html). Además, también se pueden consultar las fechas de publicación de una publicación en particular con la función [PUBLICACIONFECHA_PUBLICACION](funciones/publicacionfecha_publicacion.html).

**Obtener el litado de todas las publicaciones**

<https://servicios.ine.es/wstempus/js/ES/PUBLICACIONES>

**Obtener el listado de las publicaciones de una operación**

Por ejemplo, las publicaciones de la operación del IPC (IOE30138 / IPC / 25)

<https://servicios.ine.es/wstempus/js/ES/PUBLICACIONES_OPERACION/IPC>

**Obtener las fechas de publicación de una publicación**

Por ejemplo, de la publicación "Índice de Precios de Consumo" (Id=8)

<https://servicios.ine.es/wstempus/js/ES/PUBLICACIONFECHA_PUBLICACION/8?tip=A>
