---
title: "DATOS_SERIE"
sidebar: api-json
---

Obtener datos para una serie específica

## Inputs

Código identificativo de la serie. Para obtener el código de una serie vea [Obtención del identificador de una serie utilizando INEbase](../codigos_identificadores.html#obtenci%C3%B3n-del-identificador-de-una-serie-utilizando-inebase-s%C3%B3lo-tempus3)

## Parámetros

### **nult**

Devolver los n últimos datos o periodos.

### **det**

Ofrece mayor nivel de detalle de la información mostrada. Valores válidos son 0, 1 y 2

### **tip**

Obtener la respuesta de las peticiones de modo más amigable (‘A’), incluir metadatos (‘M’) o ambos (‘AM’)

### **date**

Obtener los datos entre dos fechas. El formato es date=aaaammdd:aaaammdd

## Salida

Información de la serie: Nombre de la serie, identificador Tempu3 de la unidad, identificador Tempus3 de la escala, fecha, identificador Tempus3 del tipo de dato, identificador Tempus3 del periodo, año y valor (dato).

## Ejemplos

Devuelve el último periodo de la serie con código IPC251856

<https://servicios.ine.es/wstempus/js/ES/DATOS_SERIE/IPC251856?nult=1>

Devuelve los últimos 5 periodos de la serie con código IPC251856

<https://servicios.ine.es/wstempus/js/ES/DATOS_SERIE/IPC251856?nult=5>

Devuelve el último periodo de la serie con código IPC251856 con salida amigable y metadatos

<https://servicios.ine.es/wstempus/js/ES/DATOS_SERIE/IPC251856?nult=1&tip=AM>

Devuelve el último periodo de la serie con código IPC251856 y nivel de detalle 2

<https://servicios.ine.es/wstempus/js/ES/DATOS_SERIE/IPC251856?nult=1&det=2>

Devuelve los datos entre el 01/01/2023 y el 31/12/2023

<https://servicios.ine.es/wstempus/js/ES/DATOS_SERIE/IPC251856?date=20230101:20231231&tip=A>

Devuelve los datos a partir del 01/01/2024

<https://servicios.ine.es/wstempus/js/ES/DATOS_SERIE/IPC251856?date=20240101:&tip=A>
