---
title: "SERIES_OPERACION"
sidebar: api-json
---

Obtener todas las series de una operación

## Input

Código identificativo de la operación. Para consultar las operaciones disponibles vea [OPERACIONES_DISPONIBLES](operaciones_disponibles.html)

## Parámetros

### **det**

Ofrece mayor nivel de detalle de la información mostrada. Valores válidos del parámetro: 0, 1 y 2

### **tip**

Obtener la respuesta de las peticiones de modo más amigable (‘A’), incluir metadatos (‘M’) o ambos (‘AM’)

### **page**

La respuesta está paginada. Se ofrece un máximo de 500 elementos por página para no ralentizar la respuesta. Para consultar las páginas siguientes, se utiliza el parámetro page

## Salida

Información de las series: identificadores Tempus3 de la serie, identificador Tempus3 de la operación, nombre de la serie, número de decimales que se van a visualizar para los datos de esa serie, identificador Tempus3 de la periodicidad, identificador Tempus3 de la publicación, identificador Tempsu3 de la clasificación, identificador Tempus3 de la escala e identificador Tempus3 de la unidad.

## Ejemplos

Consulta de las primeras 500 series pertenecientes a la operación IPC (IOE30138 / IPC / 25)

<https://servicios.ine.es/wstempus/js/ES/SERIES_OPERACION/IPC?page=1>

Consulta de las segundas 500 series pertenecientes a la operación IPC (IOE30138 / IPC / 25)

<https://servicios.ine.es/wstempus/js/ES/SERIES_OPERACION/IPC?page=2>

Consulta con máximo nivel de detalle

<https://servicios.ine.es/wstempus/js/ES/SERIES_OPERACION/IPC?page=1&det=2>

Consulta con salida amigable

<https://servicios.ine.es/wstempus/js/ES/SERIES_OPERACION/IPC?page=1&det=2&tip=A>

Consulta con metadatos y salida amigable

<https://servicios.ine.es/wstempus/js/ES/SERIES_OPERACION/IPC?page=1&tip=AM>
